name: in_date_utils
description: Utils for DateTime. Easily modify, check and copy dates. Get numbers of days in year/month. And mony more.
version: 0.1.1+1
homepage: https://github.com/innim/
repository: https://github.com/Innim/in_date_utils
issue_tracker: https://github.com/Innim/in_date_utils/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.14.2
  pedantic: ^1.9.2