name: in_date_utils
description: Utils for DateTime. Easily modify, check and copy dates. Get
  numbers of days in year/month. And many more.
version: 1.2.4+1
homepage: https://github.com/innim/
repository: https://github.com/Innim/in_date_utils
issue_tracker: https://github.com/Innim/in_date_utils/issues

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  clock: ^1.1.1
  meta: ^1.3.0

dev_dependencies:
  innim_lint: ^0.3.1
  test: ^1.16.0
  timezone: ^0.9.2
