name: in_date_utils
description: Utils for DateTime. Easily modify, check and copy dates. Get numbers of days in year/month. And mony more.
version: 1.0.1-nullsafety.0
homepage: https://github.com/innim/
repository: https://github.com/Innim/in_date_utils
issue_tracker: https://github.com/Innim/in_date_utils/issues

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  test: ^1.16.0-nullsafety.12
  pedantic: ^1.10.0-nullsafety.3
