name: in_date_utils
description: Utils for DateTime.
version: 0.1.0
homepage: https://github.com/innim/
repository: https://github.com/Innim/in_date_utils
issue_tracker: https://github.com/Innim/in_date_utils/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  date_utils: ^0.1.0

dev_dependencies:
  test: ^1.14.2
  pedantic: ^1.9.2